---
  - name: Download and extract adw-gtk3 theme
    ansible.builtin.unarchive:
      src: "{{ adw_gtk3 }}"
      dest: "/usr/share/themes/"
      remote_src: yes
    become: yes

  - name: Download and extract Tela icons
    ansible.builtin.unarchive:
      src: https://github.com/vinceliuice/Tela-icon-theme/archive/refs/heads/master.zip
      dest: "{{ playbook_dir }}"
      remote_src: yes

  - name: Run the Tela installation script
    ansible.builtin.shell: Tela-icon-theme-master/install.sh

  - name: Remove files for manual download
    file:
      path: "{{ playbook_dir }}/Tela-icon-theme-master"
      state: absent