---
  - name: Remove files for manual download
    file:
      path: "{{ playbook_dir }}/{{ item }}"
      state: absent
    loop:
      - "google-chrome-stable_current_x86_64.rpm"
      - "vscode.repo.j2"
      - "gitkraken-amd64.rpm"
